language: node_js
node_js:
- '11'
- '10'
- '9'
- '8'
script:
- "./travis-test"
env:
  global:
  - secure: QU5N70pFqK5qsMac4Apew69Xkqy8zV6VPDJSyfkWz3GnhpPZPiYP8+IegJSNqBfadKX2RYzCQSjxC/vhxHO/Knbc5/hHN+yomwMq8SGludLM0SOlFxTYbl5UmxfmMcOYPghkJcmXI/pc0rKHXn+lKKJilx1s7c50Vk5Cn4gJv7MW//kGl23+Mufo6SwhTZPlnWfgl+fZZ3LpxpveQgewwGKj5i3iZ0QVS0hBkeSYDEgJKkyFQJED/tKX5EOIwD21/Vo6+D84ASBKzUGyTJvHZXfAbygV1WihQeAJ3TM4bqjaiDFC8N9s9LbAhHftSLJU5nBJEryZhF4YwkIuFZpDp2OtKnJGgdWaBh3kBhHLWkLu6MREJUclSEe9iUbVyDi9GXF7DH736++2imvhxwblQ+puOEsJn7goVhiJI1NqhpxoVObxy8WMdTKjsUs4YD+dJTHNA884zV37auDiSV1ibWHmQkzlyVJinzmqLgqgs1NYcKyTb4YQ6AOPqaL/nOPzqyPCJSGOVNkp2xnfPPfb1/BYkdzVgnsjBmNUBs3NngL8mc91Fhj08yNAJH1o3q/i27uViy9Z5y1PuKbiMyVdgP13vXR9WQ6BNUJYRXdaGld+VjRxvMhWFCxrTP2dIldq/6Bw9bSmYCDjmgbTotHSIhtNhXTrsytJ+dCDUY6F3Fk=
  - secure: Z+hCiqRHCVZNTrhw9kg6bGWOdYCi0cCmle87aTmlTHHohslUHiBojJQ8fzCk+0ZQ0LHgjJnq/k49PAnTjguWP1/ea1a32LLenPi6xuTB0S2udRluYyfzUwD/xXx27gZGzfQERjhWi8fRdUo5UDsCg104GoQie0/tN4vq3ERh37bBuyKap25zOlypVd4iwaXT4/nAz8On5nqRaCrRyoSJxSAWvmZoA3Be9b4wViFgruupXgsOM55tFiRFy/sSBhnTwBrni+Q3smJsM+HG1PkpDz/pF0aAqYxRrhzQvmeJ6Vdeyzq8j2TkrC0xXanJ7sixSoGwGX3jUrA6sF6yO4MPixXXzB8b01p5RGsbHweTdS8T/CLig08nFPNVGDBtF3KQC6uDJ23DXSvPL46RuIn/ilK8X4jqcXZGZij4aUz6wloZmpn/6M7nL4aMOUrKbBKPoAIeDntUTGqkOsYq5yTPy9whX1UoUw6Oz2r8rgWcOZFduU96EBjGx1su8spq/xdOLzuVUJrY7iySqfe03eCmrwn/nws/1uTvhao1Eb47HDp29FGwsQFs5AgmLqjThLEcUqSuvrH3QKG3vVT0pIXJ5Bwut132KIgOAMfUW7nftySdGaG759ZnSuMjSB3k7CVFzqjF+xHhTLLeui6p4iuqevkTxaB6b+uuCoTfNNJNdGg=
