version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          pip install --user mkdocs mkdocs-material
          git config --global user.email $GH_EMAIL
          git config --global user.name $GH_NAME
          mkdocs gh-deploy

workflows:
  version: 2
  build-docs:
    jobs:
      - build:
          filters:
            branches:
              only: master

