version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          git config --global user.email $GH_EMAIL
          git config --global user.name $GH_USER
          ls ~/repo
          pwd
          docker run --rm -it -v ~/.ssh:/root/.ssh -v ~/repo:/docs squidfunk/mkdocs-material gh-deploy

workflows:
  version: 2
  build-docs:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/

