version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          pip install --user --upgrade pip
          pip install --user mkdocs
          pip install --user mkdocs-material
          git config --global user.email $GH_EMAIL
          git config --global user.name $GH_USER
          mkdocs gh-deploy

workflows:
  version: 2
  build-docs:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/

