blank_issues_enabled: false
contact_links:
  -
    about: "Alternatively, you can use the Dynamoose Community Slack."
    name: Chat
    url: "https://join.slack.com/t/dynamoose/shared_invite/enQtODM4OTI0MTc1NDc3LWI3MmNhMThmNmJmZDk5MmUxOTZmMGEwNGQzNTRkMjhjZGJlNGM5M2JmZjMzMzlkODRhMGY3MTQ5YjQ2Nzg3YTY"
