name: Cron

on:
  schedule:
    - cron: "5 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 7 days with no activity. Remove stale label or comment or this will be closed in 3 days.'
          stale-issue-label: 'status:stale'
          exempt-issue-labels: 'status:not-stale,status:todo,status:triage,type:discussion'
          stale-pr-message: 'This pull request is stale because it has been open 7 days with no activity. Remove stale label or comment or this will be closed in 3 days.'
          stale-pr-label: 'status:stale'
          exempt-pr-labels: 'status:not-stale,status:todo,status:triage,type:discussion'
          days-before-stale: 7
          days-before-close: 3
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.3.2
      with:
        stable_branch: 'main'
        development_branch: 'v3'
        allow_ff: true
        user_name: 'GitHub Actions'
        user_email: 'actions@github.com'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
