name: Source Map Parser
on:
  issue_comment:
    types: [created]

jobs:
  parse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd utils/source-map-stacktrace-parser && npm install
      - run: node utils/source-map-stacktrace-parser/index.js
        id: parser
        outputs:
          outputtrace:
            description: "The outputted stack trace"
        with:
          comment: ${{ github.event.comment.body }}
      - name: Comment Action
        uses: JungWinter/comment@v1.1.0
        if: ${{ steps.parser.outputs.outputtrace != '' }}
        with:
          type: create
          body: "@${{ github.event.comment.user.login }} Here is your parsed stack trace you requested:\n${{ steps.parser.outputs.outputtrace }}"
          issue_number: "${{ github.event.issue.number }}"
          token: ${{ secrets.GITHUB_TOKEN }}
